<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260605115808 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, email VARCHAR(180) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, firstname VARCHAR(255) NOT NULL, lastname VARCHAR(255) NOT NULL, phone_number VARCHAR(255) DEFAULT NULL, github VARCHAR(255) DEFAULT NULL, google_drive VARCHAR(255) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "user" (email)');
        $this->addSql('CREATE TABLE absences (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, start_date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, end_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, document_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9C0EFFFA76ED395 ON absences (user_id)');
        $this->addSql('CREATE INDEX IDX_F9C0EFFFC33F7837 ON absences (document_id)');
        $this->addSql('CREATE TABLE attendance (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, student_id INT NOT NULL, promotion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6DE30D91CB944F1A ON attendance (student_id)');
        $this->addSql('CREATE INDEX IDX_6DE30D91139DF194 ON attendance (promotion_id)');
        $this->addSql('CREATE TABLE attendance_signature (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, date TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, promotion_id INT NOT NULL, document_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_DB0CAB7BCB944F1A ON attendance_signature (student_id)');
        $this->addSql('CREATE INDEX IDX_DB0CAB7B139DF194 ON attendance_signature (promotion_id)');
        $this->addSql('CREATE INDEX IDX_DB0CAB7BC33F7837 ON attendance_signature (document_id)');
        $this->addSql('CREATE TABLE documents (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, type VARCHAR(255) DEFAULT NULL, title VARCHAR(255) NOT NULL, path VARCHAR(255) DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2B07288A76ED395 ON documents (user_id)');
        $this->addSql('CREATE TABLE grades (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, grade VARCHAR(255) DEFAULT NULL, comments TEXT DEFAULT NULL, submission VARCHAR(255) DEFAULT NULL, update_history TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, status VARCHAR(255) NOT NULL, project_id INT NOT NULL, student_id INT NOT NULL, promotion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3AE36110166D1F9C ON grades (project_id)');
        $this->addSql('CREATE INDEX IDX_3AE36110CB944F1A ON grades (student_id)');
        $this->addSql('CREATE INDEX IDX_3AE36110139DF194 ON grades (promotion_id)');
        $this->addSql('CREATE TABLE notification_recipients (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, is_read BOOLEAN NOT NULL, read_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, notification_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EF1497E6EF1A9D84 ON notification_recipients (notification_id)');
        $this->addSql('CREATE INDEX IDX_EF1497E6A76ED395 ON notification_recipients (user_id)');
        $this->addSql('CREATE TABLE notifications (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, message TEXT DEFAULT NULL, type VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, sender_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6000B0D3F624B39D ON notifications (sender_id)');
        $this->addSql('CREATE TABLE presence (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, signed_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, student_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6977C7A5CB944F1A ON presence (student_id)');
        $this->addSql('CREATE TABLE projects (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(255) NOT NULL, visibility BOOLEAN NOT NULL, description TEXT NOT NULL, google_drive VARCHAR(255) DEFAULT NULL, due_date TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE projects_promotions (projects_id INT NOT NULL, promotions_id INT NOT NULL, PRIMARY KEY (projects_id, promotions_id))');
        $this->addSql('CREATE INDEX IDX_5CA4A1CE1EDE0F55 ON projects_promotions (projects_id)');
        $this->addSql('CREATE INDEX IDX_5CA4A1CE10007789 ON projects_promotions (promotions_id)');
        $this->addSql('CREATE TABLE promotion_users (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, user_id INT NOT NULL, promotion_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7485D1B4A76ED395 ON promotion_users (user_id)');
        $this->addSql('CREATE INDEX IDX_7485D1B4139DF194 ON promotion_users (promotion_id)');
        $this->addSql('CREATE TABLE promotions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, professor_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_EA1B30347D2D84D5 ON promotions (professor_id)');
        $this->addSql('CREATE TABLE user_actions (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, action TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_5D45EFE5A76ED395 ON user_actions (user_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('ALTER TABLE absences ADD CONSTRAINT FK_F9C0EFFFA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE absences ADD CONSTRAINT FK_F9C0EFFFC33F7837 FOREIGN KEY (document_id) REFERENCES documents (id)');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D91CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attendance ADD CONSTRAINT FK_6DE30D91139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attendance_signature ADD CONSTRAINT FK_DB0CAB7BCB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attendance_signature ADD CONSTRAINT FK_DB0CAB7B139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE attendance_signature ADD CONSTRAINT FK_DB0CAB7BC33F7837 FOREIGN KEY (document_id) REFERENCES documents (id)');
        $this->addSql('ALTER TABLE documents ADD CONSTRAINT FK_A2B07288A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE36110166D1F9C FOREIGN KEY (project_id) REFERENCES projects (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE36110CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE grades ADD CONSTRAINT FK_3AE36110139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification_recipients ADD CONSTRAINT FK_EF1497E6EF1A9D84 FOREIGN KEY (notification_id) REFERENCES notifications (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notification_recipients ADD CONSTRAINT FK_EF1497E6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT FK_6000B0D3F624B39D FOREIGN KEY (sender_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE presence ADD CONSTRAINT FK_6977C7A5CB944F1A FOREIGN KEY (student_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE projects_promotions ADD CONSTRAINT FK_5CA4A1CE1EDE0F55 FOREIGN KEY (projects_id) REFERENCES projects (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE projects_promotions ADD CONSTRAINT FK_5CA4A1CE10007789 FOREIGN KEY (promotions_id) REFERENCES promotions (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE promotion_users ADD CONSTRAINT FK_7485D1B4A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE promotion_users ADD CONSTRAINT FK_7485D1B4139DF194 FOREIGN KEY (promotion_id) REFERENCES promotions (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE promotions ADD CONSTRAINT FK_EA1B30347D2D84D5 FOREIGN KEY (professor_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_actions ADD CONSTRAINT FK_5D45EFE5A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE absences DROP CONSTRAINT FK_F9C0EFFFA76ED395');
        $this->addSql('ALTER TABLE absences DROP CONSTRAINT FK_F9C0EFFFC33F7837');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D91CB944F1A');
        $this->addSql('ALTER TABLE attendance DROP CONSTRAINT FK_6DE30D91139DF194');
        $this->addSql('ALTER TABLE attendance_signature DROP CONSTRAINT FK_DB0CAB7BCB944F1A');
        $this->addSql('ALTER TABLE attendance_signature DROP CONSTRAINT FK_DB0CAB7B139DF194');
        $this->addSql('ALTER TABLE attendance_signature DROP CONSTRAINT FK_DB0CAB7BC33F7837');
        $this->addSql('ALTER TABLE documents DROP CONSTRAINT FK_A2B07288A76ED395');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE36110166D1F9C');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE36110CB944F1A');
        $this->addSql('ALTER TABLE grades DROP CONSTRAINT FK_3AE36110139DF194');
        $this->addSql('ALTER TABLE notification_recipients DROP CONSTRAINT FK_EF1497E6EF1A9D84');
        $this->addSql('ALTER TABLE notification_recipients DROP CONSTRAINT FK_EF1497E6A76ED395');
        $this->addSql('ALTER TABLE notifications DROP CONSTRAINT FK_6000B0D3F624B39D');
        $this->addSql('ALTER TABLE presence DROP CONSTRAINT FK_6977C7A5CB944F1A');
        $this->addSql('ALTER TABLE projects_promotions DROP CONSTRAINT FK_5CA4A1CE1EDE0F55');
        $this->addSql('ALTER TABLE projects_promotions DROP CONSTRAINT FK_5CA4A1CE10007789');
        $this->addSql('ALTER TABLE promotion_users DROP CONSTRAINT FK_7485D1B4A76ED395');
        $this->addSql('ALTER TABLE promotion_users DROP CONSTRAINT FK_7485D1B4139DF194');
        $this->addSql('ALTER TABLE promotions DROP CONSTRAINT FK_EA1B30347D2D84D5');
        $this->addSql('ALTER TABLE user_actions DROP CONSTRAINT FK_5D45EFE5A76ED395');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE absences');
        $this->addSql('DROP TABLE attendance');
        $this->addSql('DROP TABLE attendance_signature');
        $this->addSql('DROP TABLE documents');
        $this->addSql('DROP TABLE grades');
        $this->addSql('DROP TABLE notification_recipients');
        $this->addSql('DROP TABLE notifications');
        $this->addSql('DROP TABLE presence');
        $this->addSql('DROP TABLE projects');
        $this->addSql('DROP TABLE projects_promotions');
        $this->addSql('DROP TABLE promotion_users');
        $this->addSql('DROP TABLE promotions');
        $this->addSql('DROP TABLE user_actions');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
